# -*- coding: utf-8 -*-
"""Python Dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1Rd7a9DDztJjJC_3LC523OGPQsP04dO
"""



"""# Exercise #2 Python Dictionaries

### Dictionary mapping base 10 to binary

Exercise
Write a function to create a dictionary of binary values of decimal of 0 to 15

The decimal number should be the key and the binary number should be the value Example Output: { 0: “0000”, 1: “0001”, 2: “0010”, … }
"""

list_key = []
list_binary = []
def create_binary_dict(end):
  for n in range(end+1):
    list_key.append(n)
    list_binary.append(bin(n)[2:])
  combined_list = zip(list_key,list_binary)
  print(dict(combined_list))

create_binary_dict(15)

def binary_dict():

  #List of numbers
  numbers = list(range(16))

  #List of Binary numbers
  # binaries = []

  #Loop over base 10 numbers, apply bin() to each
  binaries = [bin(number)[2:] for number in numbers]
  # for number in numbers:

  #Loop over numbers

    # #apply bin()
    # binary_num = bin(number)

    # #add them to list
    # binaries.append(binary_num[2:])

  #Zip together and covert to dictionary
  return dict(zip(numbers, binaries))

zipped_list = binary_dict()
zipped_list

