# -*- coding: utf-8 -*-
"""python-lists-and-tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq9Wii7sU1GZyBIm7d2cO89qP0rJ7eyw

# Python Lists and Tuples

Exercise
Write a function to create two lists, one for the alphabet variable below and one for the index of the alphabet variable

Join the two lists together and return a list of tuples L = ‘abcdefghijklmnopqrstuvwxyz’ Example Output = [(1, ‘a’), (2, ‘b’), (3, ‘c’), ...]
"""

# First attempt at solution

def create_two_lists():
  alpha = 'abcdefghijklmnopqrstuvwxyz'
  list_index = []
  list_alpha = []
  for letter in alpha:
    list_alpha.append(letter)
  for n in range(1, len(alpha)+1):
    list_index.append(n)
  return (list(zip(list_index,list_alpha)))

alphabet = create_two_lists()

alphabet

# Second attempt following Jsoh
# creating a function to make a list

alpha = "abcdefghijklmnopqrstuvwxyz"

def alpha_index(alphas):
  indices = range(1, len(alphas)+1)
  return list(zip(indices, alphas))

alpha_index(alpha)

